// Imports all effect classes and registers them. Import this file once at app startup.
import { EffectRegistry } from '../core/registry.js';

import { ClearEffect      } from './clear.js';
import { FadeoutEffect    } from './fadeout.js';
import { BlurEffect       } from './blur.js';
import { BrightnessEffect } from './brightness.js';
import { InvertEffect     } from './invert.js';
import { MirrorEffect     } from './mirror.js';
import { MosaicEffect     } from './mosaic.js';
import { SimpleEffect     } from './simple.js';
import { StarfieldEffect  } from './starfield.js';
import { SuperScopeEffect } from './superscope.js';
import { CommentEffect       } from './comment.js';
import { BufferSaveEffect    } from './buffer-save.js';
import { GrainEffect         } from './grain.js';
import { ChannelShiftEffect  } from './channel-shift.js';
import { ColorModifierEffect } from './color-modifier.js';
import { BassSpinEffect       } from './bass-spin.js';
import { BlitEffect          } from './blit.js';
import { TimescopeEffect     } from './timescope.js';
import { DotGridEffect       } from './dot-grid.js';
import { DotPlaneEffect      } from './dot-plane.js';
import { MovingParticleEffect} from './moving-particle.js';
import { MovementEffect      } from './movement.js';
import { WaterEffect         } from './water.js';
import { WaterBumpEffect     } from './waterbump.js';
import { BumpEffect          } from './bump.js';
import { ColorfadeEffect       } from './colorfade.js';
import { ColorReductionEffect } from './color-reduction.js';
import { ColorClipEffect      } from './color-clip.js';
import { ContrastEffect       } from './contrast.js';
import { DDMEffect            } from './ddm.js';
import { EffectListEffect    } from './effect-list.js';
import { InterferencesEffect  } from './interferences.js';
import { DynamicMovementEffect } from './dynamic-movement.js';
import { FastBrightnessEffect  } from './fast-brightness.js';
import { InterleaveEffect      } from './interleave.js';
import { MultiplierEffect      } from './multiplier.js';
import { UniqueToneEffect      } from './unique-tone.js';
import { RotoBltEffect         } from './roto-blitter.js';
import { ScatterEffect         } from './scatter.js';
import { DynamicShiftEffect    } from './dynamic-shift.js';
import { VideoDelayEffect      } from './video-delay.js';
import { CustomBPMEffect       } from './custom-bpm.js';
import { OnBeatClearEffect     } from './onbeat-clear.js';
import { MultiDelayEffect      } from './multi-delay.js';
import { SetRenderModeEffect   } from './set-render-mode.js';
import { ConvolutionEffect     } from './convolution.js';
import { ColormapEffect        } from './colormap.js';
import { MultiFilterEffect     } from './multi-filter.js';
import { AddBordersEffect      } from './add-borders.js';
import { TexerEffect           } from './texer.js';
import { Texer2Effect          } from './texer2.js';
import { TriangleEffect        } from './triangle.js';
import { NormalizeEffect       } from './normalize.js';
import { RingEffect            } from './ring.js';
import { OscilloscopeStarEffect } from './oscilloscope-star.js';
import { PictureEffect          } from './picture.js';
import { Picture2Effect         } from './picture2.js';
import { RotatingStarsEffect    } from './rotating-stars.js';
import { DotFountainEffect    } from './dot-fountain.js';
import { TextEffect           } from './text.js';
import { Effect } from './effect.js';

EffectRegistry.register('Effect List',   EffectListEffect);
EffectRegistry.register('Add Borders',        AddBordersEffect);
EffectRegistry.register('Bass Spin',     BassSpinEffect);
EffectRegistry.register('Blit',          BlitEffect);
EffectRegistry.register('Blur',          BlurEffect);
EffectRegistry.register('Brightness',    BrightnessEffect);
EffectRegistry.register('Buffer Save',   BufferSaveEffect);
EffectRegistry.register('Bump',          BumpEffect);
EffectRegistry.register('Channel Shift', ChannelShiftEffect);
EffectRegistry.register('Clear',         ClearEffect);
EffectRegistry.register('Colorfade',        ColorfadeEffect);
EffectRegistry.register('Color Clip',       ColorClipEffect);
EffectRegistry.register('Color Map',          ColormapEffect);
EffectRegistry.register('Color Modifier',ColorModifierEffect);
EffectRegistry.register('Color Reduction',  ColorReductionEffect);
EffectRegistry.register('Comment',       CommentEffect);
EffectRegistry.register('Convolution Filter', ConvolutionEffect);
EffectRegistry.register('Contrast',                    ContrastEffect);
EffectRegistry.register('Custom BPM',       CustomBPMEffect);
EffectRegistry.register('Dot Grid',      DotGridEffect);
EffectRegistry.register('Dot Plane',     DotPlaneEffect);
EffectRegistry.register('Dot Fountain',       DotFountainEffect);
EffectRegistry.register('Dynamic Distance Modifier',   DDMEffect);
EffectRegistry.register('Dynamic Movement', DynamicMovementEffect);
EffectRegistry.register('Dynamic Shift',    DynamicShiftEffect);
EffectRegistry.register('Fadeout',       FadeoutEffect);
EffectRegistry.register('Fast Brightness',  FastBrightnessEffect);
EffectRegistry.register('Grain',         GrainEffect);
EffectRegistry.register('Interferences',    InterferencesEffect);
EffectRegistry.register('Interleave',       InterleaveEffect);
EffectRegistry.register('Invert',        InvertEffect);
EffectRegistry.register('Mirror',        MirrorEffect);
EffectRegistry.register('Mosaic',        MosaicEffect);
EffectRegistry.register('Movement',      MovementEffect);
EffectRegistry.register('Moving Particle',MovingParticleEffect);
EffectRegistry.register('Multi Delay',      MultiDelayEffect);
EffectRegistry.register('Multi Filter',       MultiFilterEffect);
EffectRegistry.register('Multiplier',       MultiplierEffect);
EffectRegistry.register('Normalize',          NormalizeEffect);
EffectRegistry.register('OnBeat Clear',     OnBeatClearEffect);
EffectRegistry.register('Oscilloscope Star',  OscilloscopeStarEffect);
EffectRegistry.register('Picture',            PictureEffect);
EffectRegistry.register('Picture II',         Picture2Effect);
EffectRegistry.register('Ring',               RingEffect);
EffectRegistry.register('Rotating Stars',    RotatingStarsEffect);
EffectRegistry.register('Roto Blitter',     RotoBltEffect);
EffectRegistry.register('Scatter',          ScatterEffect);
EffectRegistry.register('Set Render Mode',  SetRenderModeEffect);
EffectRegistry.register('Simple',        SimpleEffect);
EffectRegistry.register('Starfield',     StarfieldEffect);
EffectRegistry.register('SuperScope',    SuperScopeEffect);
EffectRegistry.register('Text',               TextEffect);
EffectRegistry.register('Texer',              TexerEffect);
EffectRegistry.register('Texer II',           Texer2Effect);
EffectRegistry.register('Timescope',     TimescopeEffect);
EffectRegistry.register('Triangle',     TriangleEffect);
EffectRegistry.register('Unique Tone',      UniqueToneEffect);
EffectRegistry.register('Video Delay',      VideoDelayEffect);
EffectRegistry.register('Water',         WaterEffect);
EffectRegistry.register('Water Bump',    WaterBumpEffect);